include(SetAppVersion)
set(DOCDIR "usr/share/doc/${CMAKE_PROJECT_NAME}-${APPLICATION_VERSION}")
set(DOC_FILES_TO_INSTALL README AUTHORS License ChangeLog TODO)
set(DOC_DIRS_TO_INSTALL examples)
set(error_message "not found. It is good for documentation purposes to create it.")

function(INSTALL_DOC_FILE_IF_EXISTS ${filename})
    if(EXISTS ${CMAKE_SOURCE_DIR}/${filename})
        message(STATUS "Found ${filename}, installing to ${DOCDIR}")
        INSTALL(FILES ${filename} DESTINATION ${DOCDIR})
    else()
        message(STATUS "Notice: file ${filename} ${error_message}")
    endif()
endfunction(INSTALL_DOC_FILE_IF_EXISTS)

function(INSTALL_DOC_DIR_IF_EXISTS ${dirname})
    if(EXISTS ${CMAKE_SOURCE_DIR}/${dirname})
        message(STATUS "Found directory ${dirname}, installing to ${DOCDIR}")
        INSTALL(DIRECTORY ${dirname} DESTINATION ${DOCDIR})
    else()
        message(STATUS "Notice: directory ${dirname} ${error_message}")
    endif()
endfunction(INSTALL_DOC_DIR_IF_EXISTS)

function(INSTALL_DOC_FILES)
    foreach(filename ${DOC_FILES_TO_INSTALL})
        INSTALL_DOC_FILE_IF_EXISTS(${filename})
    endforeach(filename)
endfunction(INSTALL_DOC_FILES)

function(INSTALL_DOC_DIRS)
    foreach(dirname ${DOC_DIRS_TO_INSTALL})
        INSTALL_DOC_DIR_IF_EXISTS(${dirname})
    endforeach(dirname)
endfunction(INSTALL_DOC_DIRS)

INSTALL_DOC_FILES()
INSTALL_DOC_DIRS()
